# SPDX-FileCopyrightText: 2021-2024 Helmholtz-Zentrum hereon GmbH
#
# SPDX-License-Identifier: CC0-1.0

image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  # replace git internal paths in order to use the CI_JOB_TOKEN
  - apt-get update -y && apt-get install -y pandoc graphviz
  - python -m pip install -U pip

test-package:
  stage: test
  script:
    - pip install build twine
    - make dist
    - twine check dist/*
  artifacts:
    name: python-artifacts
    paths:
      - "dist/*"
    expire_in: 7 days

test:
  stage: test
  variables:
    PIPENV_PIPFILE: "ci/matrix/${SCENARIO}/Pipfile"
    # disable sandboxing, otherwise chrome reports errors when the
    # container runs as root
    # https://doc.qt.io/qt-5/qtwebengine-platform-notes.html#sandboxing-support
    QTWEBENGINE_DISABLE_SANDBOX: "true"
  script:
    # install necessary libraries for pyqt
    - apt-get install -y xvfb python3-pyqt5.qtwebengine
    - pip install pipenv
    - pipenv install
    - xvfb-run make pipenv-test
  parallel:
    matrix:
      - SCENARIO:
          - default
  artifacts:
    name: pipfile
    paths:
      - "ci/matrix/${SCENARIO}/*"
    expire_in: 30 days
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

test-docs:
  stage: test
  variables:
    MPLBACKEND: "module://psyplot_gui.backend"
    # disable sandboxing, otherwise chrome reports errors when the
    # container runs as root
    # https://doc.qt.io/qt-5/qtwebengine-platform-notes.html#sandboxing-support
    QTWEBENGINE_DISABLE_SANDBOX: "true"
  script:
    # install necessary libraries for pyqt
    - apt-get install -y xvfb python3-pyqt5.qtwebengine
    - make dev-install
    # install PyQt5 (not part of requirements.txt because this is complicated
    # to install on different platforms)
    - pip install PyQt5 PyQtWebEngine
    - xvfb-run make -C docs html
    - xvfb-run make -C docs linkcheck
  artifacts:
    paths:
    - docs/_build


deploy-package:
  stage: deploy
  needs:
    - test-package
    - test-docs
    - test
  only:
    - main
  script:
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
