{% set data = load_setup_py_data() %}
{% set name = "psy-view" %}

package:
  name: {{ name|lower }}
  version: {{ data.get('version') }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('CONDA_PY') }}{% if environ.get("BUILD_STR_END") %}_{{ environ.get("BUILD_STR_END") }}{% endif %}
  entry_points:
    - psy-view = psy_view:main
  skip: true  # [py == 36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - psyplot-gui >=1.3.0
    - psy-maps >=1.3.0
    - netcdf4

test:
  imports:
    - psy_view
    - psy_view.ds_widget

  requires:
    - pytest
    - pytest-cov
    - pytest-qt
    - codecov
    - dask
    - netcdf4
    - seaborn
    - pillow
    - psy-maps
  source_files:
    - tests

  commands:
    - psy-view --help
    - pytest -sv --cov=psy_view
    - codecov

app:
  entry: psy-view
  icon: logo.png
  summary: Quick-view for netCDF files
  type: desk

about:
  home: https://github.com/psyplot/psy-view
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: ncview-like interface to psyplot

  description: |
    This package provides a graphical user interface to quickly visualize the
    contents of a netCDF file
  doc_url: http://psyplot.github.io/psy-view
  dev_url: https://github.com/psyplot/psy-view
