name: psy-view-docs
channels:
    - local
    - psyplot/label/master
    - conda-forge
dependencies:
    - python=3.8
    - sphinx
    - sphinx_rtd_theme
    - psy-view
    - autodocsumm
    - sphinx-argparse
