channels:
- psyplot/label/master
- psyplot
- manics # Used by jupyter-desktop-server
- conda-forge
dependencies:
- psy-maps
- psyplot-gui
- netcdf4
- pip
- ncview
- matplotlib>=3.3
- cartopy>=0.18

# Required for jupyter-desktop-server
- websockify
- pip:
    - jupyter-desktop-server
