#!/bin/bash

set -euo pipefail

mkdir -p $HOME/Desktop

cp -r tests/*.nc $HOME/Desktop

python -m pip install ./

cat > $HOME/Desktop/Psy-View.desktop << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Psy-View
Exec=$(which psy-view) %f
Icon=$HOME/icon/psy-view.svg
Path=$HOME/Desktop
MimeType=application/x-netcdf;
EOF

cat > $HOME/Desktop/Psyplot.desktop << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Psyplot
Exec=$(which psyplot) %f
Icon=$HOME/icon/psyplot.svg
Path=$HOME/Desktop
MimeType=application/x-netcdf;
EOF

chmod u+x $HOME/Desktop/Psyplot.desktop $HOME/Desktop/Psy-View.desktop

# associate default applications
mkdir -p $HOME/.local/share/applications/
ln -s $HOME/Desktop/Psyplot.desktop $HOME/.local/share/applications/
ln -s $HOME/Desktop/Psy-View.desktop $HOME/.local/share/applications/

cat > $HOME/.config/mimeapps.list << EOF
[Default Applications]
application/x-netcdf=Psy-View.Desktop

[Added Associations]
application/x-netcdf=Psy-View.desktop;application/x-netcdf=Psyplot.desktop;
EOF
