#!/bin/bash

set -euo pipefail

mkdir -p $HOME/Desktop

cp -r tests/*.nc $HOME/Desktop

python -m pip install ./

cat > $HOME/Desktop/Psy-View.desktop << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Psy-View
Exec=$(which psy-view) %f
Icon=$HOME/icon/psy-view.svg
Path=$HOME/Desktop
MimeType=application/x-netcdf;
EOF

cat > $HOME/Desktop/Psyplot.desktop << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Psyplot
Exec=$(which psyplot) %f
Icon=$HOME/icon/psyplot.svg
Path=$HOME/Desktop
MimeType=application/x-netcdf;
EOF

chmod u+x $HOME/Desktop/Psyplot.desktop $HOME/Desktop/Psy-View.desktop

# associate default applications
mkdir -p $HOME/.local/share/applications/
ln -s $HOME/Desktop/Psyplot.desktop $HOME/.local/share/applications/
ln -s $HOME/Desktop/Psy-View.desktop $HOME/.local/share/applications/

cat > $HOME/.config/mimeapps.list << EOF
[Default Applications]
application/x-netcdf=Psy-View.Desktop

[Added Associations]
application/x-netcdf=Psy-View.desktop;application/x-netcdf=Psyplot.desktop;
EOF

# create a demo preset
mkdir -p $HOME/.config/psyplot/presets
cat > $HOME/.config/psyplot/presets/EUR-temperature.yml << EOF
clabel: '%(long_name)s %(units)s'
cmap: YlOrRd
datagrid: k-
lonlatbox: Europe
lsm:
  coast:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  land:
  - 0.6666666666666666
  - 0.3333333333333333
  - 0.0
  - 1.0
  ocean:
  - 0.592156862745098
  - 0.7137254901960784
  - 0.8823529411764706
  - 1.0
  res: 50m
title: '%(long_name)s over Europe'
xgrid: false
ygrid: false
EOF
